/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "primary": "#630ed4",
          "on-primary-fixed": "#25005a",
          "tertiary-fixed-dim": "#eec200",
          "surface-tint": "#732ee4",
          "on-primary": "#ffffff",
          "on-tertiary-fixed-variant": "#574500",
          "tertiary-container": "#cea700",
          "surface-container-high": "#e2e7ff",
          "terminal-green": "#4ADE80",
          "on-secondary": "#ffffff",
          "outline": "#7b7487",
          "inverse-on-surface": "#eef0ff",
          "surface-container-lowest": "#ffffff",
          "primary-fixed-dim": "#d2bbff",
          "on-surface": "#131b2e",
          "surface-bright": "#faf8ff",
          "on-error": "#ffffff",
          "tertiary-fixed": "#ffe083",
          "secondary": "#a43073",
          "outline-variant": "#ccc3d8",
          "surface": "#faf8ff",
          "on-secondary-fixed-variant": "#85145a",
          "primary-container": "#7c3aed",
          "surface-container-highest": "#dae2fd",
          "on-secondary-container": "#76014e",
          "on-tertiary": "#ffffff",
          "background": "#faf8ff",
          "tertiary": "#735c00",
          "primary-fixed": "#eaddff",
          "surface-variant": "#dae2fd",
          "on-primary-fixed-variant": "#5a00c6",
          "on-primary-container": "#ede0ff",
          "surface-container-low": "#f2f3ff",
          "error": "#ba1a1a",
          "on-tertiary-container": "#4e3e00",
          "surface-container": "#eaedff",
          "on-tertiary-fixed": "#231b00",
          "on-error-container": "#93000a",
          "inverse-primary": "#d2bbff",
          "surface-soft": "#F8FAFC",
          "grid-line": "#E2E8F0",
          "secondary-fixed-dim": "#ffafd3",
          "terminal-bg": "#1E1E1E",
          "secondary-fixed": "#ffd8e7",
          "error-container": "#ffdad6",
          "on-background": "#131b2e",
          "on-surface-variant": "#4a4455",
          "secondary-container": "#fc79bd",
          "surface-dim": "#d2d9f4",
          "inverse-surface": "#283044",
          "on-secondary-fixed": "#3d0026"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "margin-mobile": "20px",
          "gutter": "24px",
          "margin-desktop": "80px",
          "grid-size": "32px",
          "stack-gap": "16px"
      },
      "fontFamily": {
          "body-sm": ["Inter"],
          "headline-lg-mobile": ["Hanken Grotesk"],
          "headline-lg": ["Hanken Grotesk"],
          "display-hero": ["Hanken Grotesk"],
          "terminal-text": ["JetBrains Mono"],
          "body-md": ["Inter"],
          "label-mono": ["JetBrains Mono"]
      },
      "fontSize": {
          "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "38px", "fontWeight": "700"}],
          "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "display-hero": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
          "terminal-text": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "label-mono": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
