from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.services.chat_service import generate_rag_response
from app.memory.manager import conversation_manager

router = APIRouter()


class ChatRequest(BaseModel):
    session_id: str
    message: str


class ChatResponse(BaseModel):
    session_id: str
    response: str


@router.post("/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    """
    Main chat endpoint.
    Each request must include a session_id (UUID generated by the frontend on page load).
    Memory is automatically isolated per session_id.
    """
    if not request.session_id or not request.session_id.strip():
        raise HTTPException(status_code=400, detail="session_id is required")
    if not request.message or not request.message.strip():
        raise HTTPException(status_code=400, detail="message is required")

    try:
        answer = generate_rag_response(request.session_id, request.message)
        return ChatResponse(session_id=request.session_id, response=answer)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/chat/clear")
async def clear_chat_memory(request: ChatRequest):
    """
    Explicitly clear memory for a session.
    (Optional — generating a new session_id on page refresh achieves the same thing.)
    """
    conversation_manager.clear_session(request.session_id)
    return {"status": "success", "message": f"Memory cleared for session {request.session_id}"}
